# Well come to numpy library in python 

## Array in numpy
  to install pip install numpy

### Function/Method in numpy for array

       arange
* it generate 1-d array
* it take stop value where it start with 0 
* we change it by giving two values start(*first argument*) and stop(*second argument*)
* we can jump value by giving step(*third argument*) value
* we can use negative numbers

In [1]:
import numpy as np
my_array = np.arange(8)
print(my_array)
print(type(my_array))


[0 1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [2]:
import numpy as np
my_array = np.arange(1,8)
print(my_array)
print(type(my_array))


[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [3]:
import numpy as np
my_array = np.arange(1,8,3)
print(my_array)
print(type(my_array))


[1 4 7]
<class 'numpy.ndarray'>


     array
* it generate form list
* we can change type of data by using `dtype`
* we can create multi-dimension array

In [4]:
import numpy as np
from_list = np.array([1,2,3],dtype=np.int8)
print(from_list)
print(type(from_list))
print(type(from_list[0]))


[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.int8'>


In [5]:
import numpy as np
from_list = np.array([[1,2,3],[4,5,6]],dtype=np.int8)
array_2d = np.array((np.arange(0,8,2),np.arange(0,8,2)),dtype=np.int8)
print(from_list)
print(type(from_list))
print(type(from_list[0][0]))
print(array_2d)
print(type(array_2d))
print(type(array_2d[0][0]))


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
<class 'numpy.int8'>
[[0 2 4 6]
 [0 2 4 6]]
<class 'numpy.ndarray'>
<class 'numpy.int8'>


    empty array
* we have different methods to create empty arrays